/**
 * LIFE SCORE - the legal pages as Markdown documents (docs/legal/*.md).
 *
 * The documents are GENERATED from src/legal/legalContent.ts — the same words
 * the pop-up shows — and tests/legalContent.test.ts fails when a file differs
 * from this output. To refresh them after changing the words:
 *   node scripts/build-legal-docs.mjs
 */

import { legalPage, parseBody, type LegalBlock, type LegalSlug, type TextRun } from './legalContent';
import { LAST_UPDATED, SUB_PROCESSORS } from './subProcessors';

/** Where each page's document lives. */
export const LEGAL_DOC_PATHS: Readonly<Record<LegalSlug, string>> = {
  privacy: 'docs/legal/PRIVACY_POLICY.md',
  terms: 'docs/legal/TERMS_OF_SERVICE.md',
  cookies: 'docs/legal/COOKIE_POLICY.md',
  'acceptable-use': 'docs/legal/ACCEPTABLE_USE_POLICY.md',
  refunds: 'docs/legal/REFUND_POLICY.md',
  'do-not-sell': 'docs/legal/DO_NOT_SELL_OR_SHARE.md',
  'state-privacy': 'docs/legal/US_STATE_PRIVACY_RIGHTS.md',
};

function runs(rs: readonly TextRun[]): string {
  return rs.map((r) => (r.bold ? `**${r.text}**` : r.text)).join('');
}

function block(b: LegalBlock): string {
  return b.kind === 'paragraph' ? runs(b.runs) : b.items.map((item) => `- ${runs(item)}`).join('\n');
}

function cell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

/** One page as a Markdown document. */
export function legalMarkdown(slug: LegalSlug): string {
  const page = legalPage(slug);
  const out: string[] = [
    `# ${page.title}`,
    '',
    `**Effective:** ${page.effective}`,
    '',
    '> Generated from `src/legal/legalContent.ts` — the words the app shows. Do not edit this file by hand; change the source and run `node scripts/build-legal-docs.mjs`.',
  ];
  for (const section of page.sections) {
    out.push('', `## ${section.heading}`);
    for (const b of parseBody(section.body)) out.push('', block(b));
    if (section.widget === 'processors') {
      out.push(
        '',
        '| Supplier | What it does | What it receives | Where |',
        '|---|---|---|---|',
        ...SUB_PROCESSORS.map((p) => `| ${cell(p.name)} | ${cell(p.role)} | ${cell(p.data)} | ${cell(p.jurisdiction)} |`),
        '',
        `_Supplier list last updated ${LAST_UPDATED}._`
      );
    } else if (section.widget === 'dns-optout') {
      out.push('', '_In the app, the opt-out button appears here (footer → “Do Not Sell or Share My Personal Information”)._');
    }
  }
  return out.join('\n') + '\n';
}
