/**
 * LIFE SCORE - Freedom Education Types
 *
 * Type definitions for the 6-tab Freedom Education section
 * in the Court Order display. Shows winning metrics per category
 * with real-world examples and hero statements.
 *
 * Clues Intelligence LTD
 * © 2025-2026 All Rights Reserved
 */

import type { CategoryId } from './metrics';

// Re-export CategoryId for convenience
export type { CategoryId } from './metrics';

// ============================================================================
// FREEDOM EXAMPLE TYPES
// ============================================================================

/**
 * A single winning metric with its real-world example
 * Generated by Opus Judge during report generation
 */
export interface FreedomExample {
  metricId: string;
  metricName: string;
  metricIcon: string;
  winnerScore: number;
  loserScore: number;
  realWorldExample: string;  // AI-generated practical example
}

/**
 * Freedom data for a single category tab
 * Contains all winning metrics and the hero statement
 */
export interface CategoryFreedomData {
  categoryId: CategoryId;
  categoryName: string;
  categoryIcon: string;
  winningMetrics: FreedomExample[];
  heroStatement: string;  // AI-generated joyful summary
}

// ============================================================================
// FULL FREEDOM EDUCATION DATA
// ============================================================================

/**
 * Complete freedom education data for all 6 categories
 * Stored in judgeReport.freedomEducation
 */
export interface FreedomEducationData {
  categories: CategoryFreedomData[];
  winnerCity: string;
  loserCity: string;
  generatedAt: string;
}

// ============================================================================
// CATEGORY METADATA
// ============================================================================

/**
 * Category display metadata for tabs
 */
export interface CategoryTabInfo {
  id: CategoryId;
  name: string;
  shortName: string;
  icon: string;
}

/**
 * Static category metadata for the 6 tabs
 */
export const FREEDOM_CATEGORIES: CategoryTabInfo[] = [
  { id: 'personal_freedom', name: 'Personal Freedom', shortName: 'Personal', icon: '🗽' },
  { id: 'housing_property', name: 'Housing & Property', shortName: 'Housing', icon: '🏠' },
  { id: 'business_work', name: 'Business & Work', shortName: 'Business', icon: '💼' },
  { id: 'transportation', name: 'Transportation', shortName: 'Transport', icon: '🚇' },
  { id: 'policing_legal', name: 'Policing & Legal', shortName: 'Policing', icon: '⚖️' },
  { id: 'speech_lifestyle', name: 'Speech & Lifestyle', shortName: 'Speech', icon: '🎭' },
];

// ============================================================================
// COMPONENT PROPS
// ============================================================================

/**
 * Props for FreedomCategoryTabs component
 */
export interface FreedomCategoryTabsProps {
  activeCategory: CategoryId;
  onCategoryChange: (categoryId: CategoryId) => void;
  categories: CategoryFreedomData[];
}

/**
 * Props for FreedomMetricsList component
 */
export interface FreedomMetricsListProps {
  metrics: FreedomExample[];
  winnerCity: string;
  loserCity: string;
  categoryName: string;
}

/**
 * Props for FreedomHeroFooter component
 */
export interface FreedomHeroFooterProps {
  heroStatement: string;
  winnerCity: string;
  categoryName: string;
}
